export const productsThirdCategory = [
  {
    id: 1,
    image: 'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg',
    name: 'HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA)',
    price: 799,
    description: 'OUTSTANDING VISUALS – This FHD display with IPS technology gives you brilliant visuals and unforgettable quality; with a maximum resolution of 1920 x 1080 at 75 Hz, you’ll experience the image accuracy and wide-viewing spectrums of premium tablets and mobile devices.',
    cost: '$164.99',
    link: 'https://www.amazon.com/HP-24mh-FHD-Monitor-Built/dp/B08BF4CZSV/ref=sr_1_1?dchild=1&qid=1615011281&s=electronics&sr=1-1',
    numberOflikes: 10,
  },
  {
    id: 2,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81tjLksKixL._AC_SL1500_.jpg',
    name: 'Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PS4, & Xbox - 1-Year Rescue Service (STGX2000400)',
    price: 799,
    description: 'Easily store and access 2TB to content on the go with the Seagate Portable Drive, a USB external hard drive',
    rating: 3.8,
    link: 'https://www.amazon.com/Seagate-Portable-External-Hard-Drive/dp/B07CRG94G3/ref=sr_1_2?dchild=1&qid=1615011281&s=electronics&sr=1-2',
    numberOflikes: 10,
  },
  {
    id: 3,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81%2B0dqbDGWL._AC_SL1500_.jpg',
    name: 'Roku Express | HD Streaming Media Player with High Speed HDMI Cable and Simple Remote',
    price: 799,
    description: 'New. Peacock is now streaming on all Roku devices Streaming made easy: Roku express lets you stream free, live and premium TV over the internet right to your TV; it’s perfect for new users, secondary TVs and easy gifting but powerful enough for seasoned pros',
    rating: 3.8,
    link: 'https://www.amazon.com/Roku-Express-Streaming-Media-Player/dp/B07WVFCVJN/ref=sr_1_3?dchild=1&qid=1615011281&s=electronics&sr=1-3',
    numberOflikes: 10,
  }, {
    id: 4,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81QpkIctqPL._AC_SL1500_.jpg',
    name: 'Acer SB220Q bi 21.5 Inches Full HD (1920 x 1080) IPS Ultra-Thin Zero Frame Monitor (HDMI & VGA Port), Black',
    price: 799,
    description: '【21.5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free sync technology. No compatibility for VESA Mount',
    rating: 3.8,
    link: 'https://www.amazon.com/Acer-SB220Q-Ultra-Thin-Frame-Monitor/dp/B07CVL2D2S/ref=sr_1_4?dchild=1&qid=1615011281&s=electronics&sr=1-4',
    numberOflikes: 10,
  },
   {
    id: 5,
    image: 'https://images-na.ssl-images-amazon.com/images/I/717HLlpdcIL._AC_SL1500_.jpg',
    name: 'HP 65 | Ink Cartridge | Black | N9K02AN',
    price: 799,
    description: 'Make sure this fits by entering your model number. HP 65 ink cartridges work with: HP DeskJet 2622, 2625, 2635, 2636, 2652, 2655, 3720, 3722, 3752, 3755, 3758, 5025, 5055.',
    rating: 3.8,
    link: 'https://www.amazon.com/HP-Original-Cartridge-N9K02AN-DeskJet/dp/B01BYKUI9C/ref=sr_1_5?dchild=1&qid=1615011281&s=electronics&sr=1-5',
    numberOflikes: 10,
  },
];