export const productsFourthCategory = [
  {
    id: 1,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81dpIJZtk6L._AC_SL1500_.jpg',
    name: 'Tracki 2021 Model Mini Real time GPS Tracker. Full USA & Worldwide Coverage. for Vehicles, Car, Kids, Elderly, Child, Dogs & Motorcycles. Magnetic Small Portable Tracking Device. Monthly fee Required',
    price: 16.88,
    description: 'Unlimited distance real time tracking. Full USA & all countries worldwide coverage. International SIM card included. MONTHLY FEE of $19.95 required or as low as $9.95 for long term prepaid plans. Track Vehicles, Cars, trucks, Children, teen, spouse, dogs, elderly, motorcycle, ATV, boat, equipment, tools, employees, assets, car fleets, valuable belonging. Place in a pocket, backpack, luggage, shipment or under a car & track real-time whereabouts via iPhone, Android, Google Assistant, Amazon Alexa',
    rating: 3.8,
    link: 'https://www.amazon.com/Real-time-Tracker-Worldwide-Coverage-Portable/dp/B07N4DHFZM/ref=sr_1_1?dchild=1&qid=1615011701&s=electronics&sr=1-1',
    numberOflikes: 10,
  },
  {
    id: 2,
    image: 'https://images-na.ssl-images-amazon.com/images/I/6181t0057sL._AC_SL1500_.jpg',
    name: 'Garmin 010-02064-00 Instinct, Rugged Outdoor Watch with GPS, Features Glonass and Galileo, Heart Rate Monitoring and 3-Axis Compass, Graphite',
    price: 203.85,
    description: 'Rugged GPS watch built to withstand the toughest environments Constructed to U.S. Military standard 810G for thermal, shock and water resistance (rated to 100 meters)',
    rating: 3.8,
    link: 'https://www.amazon.com/Garmin-Instinct-Features-Monitoring-Graphite/dp/B07HYX9P88/ref=sr_1_2?dchild=1&qid=1615011701&s=electronics&sr=1-2',
    numberOflikes: 10,
  },
  {
    id: 3,
    image: 'https://images-na.ssl-images-amazon.com/images/I/61QnZ-V2enL._AC_SL1000_.jpg',
    name: 'LandAirSea 54 GPS Tracker - USA Manufactured, Waterproof Magnet Mount. Full Global Coverage. 4G LTE Real-Time Tracking for Vehicle, Asset, Fleet, Elderly and more. Subscription is required.',
    price: 29.95,
    description: 'Personal GPS for reliable tracking of people, vehicles, and/or assets Ultra-compact design | 100% Waterproof | Built-in Super Strength Magnet',
    rating: 3.8,
    link: 'https://www.amazon.com/LandAirSea-Waterproof-Magnetic-Personal-Location/dp/B06XVZ6Y4T/ref=sr_1_3?dchild=1&qid=1615011701&s=electronics&sr=1-3',
    numberOflikes: 10,
  }, {
    id: 4,
    image: 'https://images-na.ssl-images-amazon.com/images/I/515HnTDmdDL._AC_SL1000_.jpg',
    name: 'Garmin inReach Mini GPS Satellite Communicator',
    price: 326.98,
    description: 'Small, rugged, lightweight satellite communicator enables 2 way text messaging using the 100 percentage global Iridium network (satellite subscription required) Trigger an interactive SOS to the 24/7 search and rescue monitoring center (satellite subscription required)',
    rating: 3.8,
    link: 'https://www.amazon.com/Garmin-Lightweight-Handheld-Satellite-Communicator/dp/B07CR7PL54/ref=sr_1_4?dchild=1&qid=1615011701&s=electronics&sr=1-4',
    numberOflikes: 10,
  },
   {
    id: 5,
    image: 'https://images-na.ssl-images-amazon.com/images/I/71wamdtiUHL._AC_SL1500_.jpg',
    name: 'Garmin 010-01689-00 Forerunner 35; Easy-to-Use GPS Running Watch, Black',
    price: 	96.70,
    description: 'Easy-to use GPS running watch tracks how far, how fast and where you run Estimates heart rate at the wrist, all day and night, using Garmin elevate wrist heart rate technology',
    rating: 3.8,
    link: 'https://www.amazon.com/Garmin-Forerunner-Easy-Running-Watch/dp/B01KPUHBK6/ref=sr_1_5?dchild=1&qid=1615011701&s=electronics&sr=1-5',
    numberOflikes: 10,
  },
];